
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf1r\x97\xa8\xca\x11s\x01\xb6Yk\xeb}\x8a\xf3)'
    
_lr_action_items = {'THEN':([26,27,28,31,],[34,-14,-13,36,]),'SEMICOLON':([11,21,25,32,],[19,29,33,37,]),'INCASE':([0,22,38,39,],[4,4,4,4,]),'DEFAULT':([11,],[18,]),'WHEN':([4,10,42,43,],[7,15,7,15,]),'NUMBER':([18,20,23,],[25,27,27,]),'ID':([4,5,7,20,23,],[10,11,12,28,28,]),'LBRACKET':([14,34,36,],[22,38,39,]),'IFNOT':([4,8,9,10,16,17,42,43,44,45,],[-16,14,-9,-16,-12,14,-16,-16,-8,-11,]),'RBRACKET':([2,3,6,19,22,29,30,33,37,38,39,40,41,],[-3,-2,-1,-4,-15,-6,35,-5,-7,-15,-15,42,43,]),'ENDINCASE':([13,24,35,],[21,32,-10,]),'DECLARE':([0,22,38,39,],[5,5,5,5,]),'CONDITION':([12,15,],[20,23,]),'$end':([0,1,2,3,6,19,29,33,37,],[-15,0,-3,-2,-1,-4,-6,-5,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,22,38,39,],[1,30,40,41,]),'repeat':([0,22,38,39,],[2,2,2,2,]),'inCase':([0,22,38,39,],[3,3,3,3,]),'sentence':([20,23,],[26,31,]),'when1':([4,42,],[8,44,]),'ifnot':([8,17,],[13,24,]),'when2':([10,43,],[17,45,]),'declare':([0,22,38,39,],[6,6,6,6,]),'empty':([4,10,42,43,],[9,16,9,16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> declare','expresion',1,'p_expresion','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',25),
  ('expresion -> inCase','expresion',1,'p_expresion','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',26),
  ('expresion -> repeat','expresion',1,'p_expresion','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',27),
  ('declare -> DECLARE ID SEMICOLON','declare',3,'p_declare','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',31),
  ('declare -> DECLARE ID DEFAULT NUMBER SEMICOLON','declare',5,'p_declare','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',32),
  ('inCase -> INCASE when1 ifnot ENDINCASE SEMICOLON','inCase',5,'p_inCase','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',36),
  ('inCase -> INCASE ID when2 ifnot ENDINCASE SEMICOLON','inCase',6,'p_inCase','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',37),
  ('when1 -> WHEN ID CONDITION sentence THEN LBRACKET expresion RBRACKET when1','when1',9,'p_when1','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',41),
  ('when1 -> empty','when1',1,'p_when1','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',42),
  ('ifnot -> IFNOT LBRACKET expresion RBRACKET','ifnot',4,'p_ifnot','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',46),
  ('when2 -> WHEN CONDITION sentence THEN LBRACKET expresion RBRACKET when2','when2',8,'p_when2','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',50),
  ('when2 -> empty','when2',1,'p_when2','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',51),
  ('sentence -> ID','sentence',1,'p_sentence','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',55),
  ('sentence -> NUMBER','sentence',1,'p_sentence','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',56),
  ('repeat -> <empty>','repeat',0,'p_repeat','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',60),
  ('empty -> <empty>','empty',0,'p_empty','/home/santii/Desktop/Pencilduino/Pencilduino/LEX_and_YACC/yacc_Duino.py',64),
]
